# Generated by Django 4.2.6 on 2024-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.URLField(
                default="https://curie.pnnl.gov/sites/default/files/default_images/default-image_0.jpeg",
                max_length=255,
            ),
        ),
    ]
